name: Build Bulletins Schedule

on:
  schedule:
    - cron: "30 6,12,18 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install poetry
      uses: Gr1N/setup-poetry@v7
      with:
        poetry-version: 1.1.8
    - name: Cache virtualenv
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
    - name: Install python deps
      run: poetry install --no-dev
    - name: Build
      run: poetry run python -m meteo.scripts.build
    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Mise à jour `TZ=Europe/Paris date +"%d/%m à %Hh%M"`"
    - name: Push changes
      run: git push origin main
