name: Build Bulletins Schedule

on:
  schedule:
    - cron: "30 6,12,18 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.8
    - name: Install python deps
      run: poetry install --no-dev
    - name: Build
      run: poetry run python -m meteo.scripts.build
    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Updated data and rebuilt pages"
    - name: Push changes
      run: git push origin main
